# -*- coding: utf-8 -*-
"""成功.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16llHH19u03nJtqk0dZrWqIywi8LAx-6M
"""

# ╔══════════════════════════════════════════╗
# ║  儲存格 1 — 安裝依賴套件                 ║
# ╚══════════════════════════════════════════╝
print("📦 正在安裝遊戲所需套件...")
!pip install streamlit google-generativeai -q
print("✅ 套件安裝完成！")

from google.colab import userdata

# 1. 讀取你設定好的正確金鑰
my_api_key = userdata.get('GEMINI_API_KEY')

# 2. 極致完全體程式碼：八大案件大集結，側邊欄完美連動
app_code = r'''import streamlit as st
from google import genai
import random
import time

st.set_page_config(
    page_title="👓 名偵探柯南：米花町事件簿",
    layout="wide",
    initial_sidebar_state="expanded"
)

# 網頁與側邊欄樣式優化
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Noto+Sans+TC:wght=500;900&display=swap');

html, body, [data-testid="stAppViewContainer"] {
    background-color: #070c19 !important;
    background-image:
        radial-gradient(circle at 85% 15%, rgba(230, 0, 18, 0.12) 0%, transparent 45%),
        radial-gradient(circle at 15% 85%, rgba(0, 113, 188, 0.1) 0%, transparent 50%);
    color: #f1f5f9 !important;
    font-family: 'Noto Sans TC', sans-serif;
}
[data-testid="stHeader"] { background: transparent !important; }

/* 側邊欄樣式設計 */
[data-testid="stSidebar"] {
    background-color: #0b1329 !important;
    border-right: 2px solid #1e293b !important;
}
.sidebar-title {
    font-size: 1.2rem; font-weight: 900; color: #38bdf8;
    padding: 1rem 0; border-bottom: 1px solid #1e293b; margin-bottom: 1rem;
    text-align: center; font-family: 'Noto Sans TC', sans-serif;
}

.det-header {
    text-align: center; padding: 1rem 1rem 1.5rem;
    border-bottom: 3px solid #e60012; margin-bottom: 2rem;
}
.det-header-eyebrow {
    font-family: 'Bebas Neue', sans-serif; font-size: 1.1rem; letter-spacing: 0.3em; color: #0071bc;
}
.det-header h1 {
    font-size: 2.5rem; font-weight: 900; color: #ffffff;
    text-shadow: 2px 2px 0px #e60012; margin: 0.5rem 0;
}
.det-header .subtitle { font-size: 1rem; color: #94a3b8; }

.case-card {
    background: linear-gradient(135deg, #0f172a 0%, #090d16 100%);
    border: 2px solid #1e293b; border-top: 6px solid #e60012;
    border-radius: 8px; padding: 2rem; margin-bottom: 1.5rem;
    position: relative; box-shadow: 0 10px 25px rgba(0,0,0,0.5);
}
.case-stamp {
    position: absolute; top: 1.2rem; right: 1.5rem;
    font-family: 'Bebas Neue', sans-serif; font-size: 0.8rem; color: #00ff66;
    border: 2px solid #00ff66; padding: 0.2rem 0.6rem; border-radius: 4px;
    transform: rotate(-3deg);
}
.case-number { font-family: 'Bebas Neue', sans-serif; font-size: 1.1rem; color: #0071bc; }
.case-title { font-size: 1.5rem; font-weight: 900; color: #ffffff; margin-bottom: 0.5rem; }
.case-body { font-size: 1.1rem; line-height: 1.7; color: #cbd5e1; }
.case-badge { display: inline-block; background: rgba(0, 113, 188, 0.15); border: 1px solid #0071bc; color: #38bdf8; font-size: 0.75rem; padding: 0.1rem 0.5rem; margin-right: 0.4rem; border-radius: 4px; }

.clue-counter { font-weight: 900; font-size: 0.9rem; color: #00ff66; text-align: right; }

.msg-user { background: #0f172a; border: 1px solid #1e293b; border-right: 5px solid #0071bc; border-radius: 6px; padding: 0.8rem 1.2rem; font-size: 1.05rem; color: #f1f5f9; }
.msg-user .label { font-weight: 900; font-size: 0.75rem; color: #38bdf8; margin-bottom: 0.3rem; }
.msg-host { background: #111115; border: 1px solid #222227; border-left: 5px solid #475569; border-radius: 6px; padding: 0.8rem 1.2rem; }
.msg-host .label { font-weight: 900; font-size: 0.75rem; color: #94a3b8; margin-bottom: 0.3rem; }
.msg-host .verdict { font-size: 1.1rem; font-weight: 900; color: #ffffff; }

.verdict-banner { background: linear-gradient(135deg, #e60012 0%, #7a000a 100%); border: 2px solid #ffffff; border-radius: 8px; padding: 1.5rem; text-align: center; margin: 1rem 0; }
.verdict-banner .v-title { font-size: 1.6rem; font-weight: 900; color: #fff100; }
.verdict-banner .v-sub { font-size: 1.05rem; color: #ffffff; line-height: 1.6; }
.det-footer { text-align: center; font-family: 'Bebas Neue', sans-serif; font-size: 0.8rem; color: #334155; margin-top: 4rem; }
</style>
""", unsafe_allow_html=True)

REAL_GEMINI_KEY = "AUTO_INJECTED_API_KEY_HERE"

# 豪華終極庫：共 8 個精選海龜湯
PUZZLES = [
    {
        "id": "p1",
        "title": "米花大飯店：最後的海龜湯",
        "tag": "CASE #001",
        "genre": ["米花町事件", "心理盲點", "生存絕境"],
        "question": "一位船長走進餐廳，點了一碗海龜湯。喝了幾口後，他面色慘白，問店家：「這真的是海龜湯嗎？」店家回答：「是的，貨真價實的海龜湯。」船長聽完後，走出餐廳，當晚便結束了自己的生命。",
        "answer": "船長曾遭遇海難，在荒島上存活時，船員們煮了湯給他喝，謊稱是海龜湯。那實際上是已故船員的肉。此後船長再也不曾喝過海龜湯。今日他喝到真正的海龜湯，察覺味道截然不同——才明白當年自己吃的是人肉。良心崩潰，選擇了死亡。",
    },
    {
        "id": "p2",
        "title": "阿笠博士的郊遊謎題：河底的水草",
        "tag": "CASE #002",
        "genre": ["驚悚誤區", "河流悲劇"],
        "question": "男孩和女友不慎落河。他拼命伸手，抓到了什麼，卻放開了。女友沒能生還。多年後，他故地重遊，遇見河邊釣魚的老人。老人說：「這條河從來沒長過水草。」男孩聽完，縱身跳入河中。",
        "answer": "當年男孩在水中抓到柔軟飄動的東西，以為是水草而放手。老人一句話讓他驚覺——那根本不是水草，而是女友的頭髮。他親手放開了救女友的最後機會，帶著這個認知沉入了同一條河。",
    },
    {
        "id": "p3",
        "title": "工藤新一首案：消失的槍聲",
        "tag": "CASE #003",
        "genre": ["經典密室", "作案手法"],
        "question": "死者倒在密室中，胸口中彈身亡。房門從內反鎖，窗戶也關得死死的。警方抵達時，房內除了一把掉在屍體旁邊的手槍外，只有一個完全融化、變成一灘水的巨大冰塊。為什麼死者會被殺（或自殺）？",
        "answer": "這是犯人的設計。犯人利用冰塊將槍固定在特定的角度與高度，並在槍口安裝了拉線定時機關。隨著冰塊融化，支撐物消失，手槍滑落並擊發，同時也掩蓋了開槍的原始位置。冰塊融化後只剩下水，讓現場看起來像是一個完全沒有外人進入的密室。",
    },
    {
        "id": "p4",
        "title": "毛利偵探事務所：完美的證詞",
        "tag": "CASE #004",
        "genre": ["不在場證明", "視覺誤導"],
        "question": "命案發生在晚上 8 點。A 先生聲稱他當時正在酒吧喝酒，並有酒保和三名常客為他作證，證明他從 7 點半到 9 點一直坐在吧台沒離開過。然而，柯南在看過監視器後，卻說：「證詞完全沒錯，但 A 先生確實是兇手。」為什麼？",
        "answer": "A 先生利用了替身與視覺誤導。他找來一個長相打扮與他一模一樣的人坐在吧台，並故意背對鏡頭或用酒杯遮臉。酒吧內燈光昏暗，酒保和常客看到的其實是替身。A 先生本人則在 8 點時離開酒吧去犯案，隨後在 9 點前回到酒吧替換回身份。",
    },
    {
        "id": "p5",
        "title": "警視廳搜查一課：紅色的指甲油",
        "tag": "CASE #005",
        "genre": ["死亡訊息", "嫌疑盲點"],
        "question": "被害人死前留下了遺言，他用顫抖的手指沾著自己的血，在木地板上寫下了一個巨大的「4」字。警方根據這個線索逮捕了排名第四的嫌疑人，但柯南卻搖頭說：「兇手不是他，這是一個陷阱。」線索是什麼意思？",
        "answer": "這不是數字 4，而是字母 h。兇手在作案時戴著指甲保護套，被害人死前想指證的是兇手手上的『紅指甲油』。兇手為了隱藏特徵塗了特殊紅色指甲油，被害人想寫下暗示紅色指甲油手部的字母，卻因死前力氣不足，歪斜得像個 4 字，導致警方誤判。",
    },
    {
        "id": "p6",
        "title": "名門連續慘案：致命的時鐘",
        "tag": "CASE #006",
        "genre": ["機械陷阱", "時間心理學"],
        "question": "一名收藏家在書房中被毒殺，現場的時鐘剛好停在 10 點整，指針處還沾著一點微量的劇毒。警方認為兇手是在 10 點時利用時鐘下毒，但柯南卻指出：死者是在 12 點時中毒的。為什麼？",
        "answer": "兇手利用了時間差與機械陷阱。兇手在時鐘的時針與分針交疊處（即 12 點）抹上劇毒，並將時鐘撥快或撥慢。死者習慣在每天固定時間去調整家中所有時鐘，當他試圖去撥動指針時，指尖觸碰到了指針上的劇毒。至於時鐘停在 10 點，是因為兇手在案發後故意將時鐘強行轉動並卡住，製造出不在場證明。",
    },
    {
        "id": "p7",
        "title": "少年偵探團暗號：只有一人的大合照",
        "tag": "CASE #007",
        "genre": ["長曝光相機", "不自然殘影"],
        "question": "案發當天，兇手在旅遊景點拍了一張與 50 名遊客的大合照，照片日期清晰可見。警方核對照片後，確認該時間點兇手確實人在遙遠的景點，不可能回城犯案。然而柯南卻說：「這張照片反而是最直接的證據，證明他就是兇手。」為什麼？",
        "answer": "這是一張經過精心設計的長曝光照片。兇手利用景點的旅遊旺季，將相機設置在長時間曝光模式（或多重曝光），他只在相機開拍的第一秒和最後一秒出現在鏡頭前，中間則藉機溜走去犯案。照片中，他留下了殘影，但在視覺上看起來他始終站在那裡。柯南發現照片中其他人的影子長度與兇手的殘影重疊度不自然，從而戳破了虛假的合影。",
    },
    {
        "id": "p8",
        "title": "黃昏別館前奏曲：被詛咒的鋼琴聲",
        "tag": "CASE #008",
        "genre": ["氣流物理學", "真空窒息"],
        "question": "豪宅主人在密室中死於窒息。現場沒有任何掙扎痕跡，窗戶封死，門從內反鎖。奇怪的是，房間內的鋼琴在死者死亡的瞬間，自動彈奏出了一段詭異的旋律，聲音大到連鄰居都聽見了。為什麼？",
        "answer": "兇手利用了真空吸塵器與自動鋼琴。犯人預先在死者的房間內設置了大型的工業吸塵器，並將排氣管接到窗外。案發時，兇手在遠端開啟裝置，吸塵器迅速抽走房內空氣，導致死者窒息而死。同時，吸塵器產生的強大氣流經過鋼琴內部結構（如鋼琴連動裝置），氣流吹動了琴弦產生聲響。那段旋律並非有人演奏，而是氣流吹過特定鍵位發出的聲音，犯人藉此製造超自然死亡的假象。"
    }
]

# --- 歷史資料庫 (Session State) ---
if "history_sessions" not in st.session_state:
    st.session_state.history_sessions = {
        "session_1": {
            "puzzle_index": 0,
            "chat_history": [],
            "solved": False
        }
    }
if "active_session_id" not in st.session_state:
    st.session_state.active_session_id = "session_1"

# --- 左側側邊欄控制台 ---
with st.sidebar:
    st.markdown('<div class="sidebar-title">📂 偵探案卷分組目錄</div>', unsafe_allow_html=True)

    # 按鈕：開啟新案件紀錄
    if st.button("➕ 開啟全新調查紀錄", use_container_width=True):
        new_id = f"session_{int(time.time())}"
        st.session_state.history_sessions[new_id] = {
            "puzzle_index": random.randint(0, len(PUZZLES) - 1),
            "chat_history": [],
            "solved": False
        }
        st.session_state.active_session_id = new_id
        st.rerun()

    st.markdown("<br>", unsafe_allow_html=True)

    # 渲染所有歷史紀錄列表 (標題動態與當前案件的 title 智慧連動)
    for s_id, s_data in list(st.session_state.history_sessions.items()):
        associated_puzzle = PUZZLES[s_data["puzzle_index"]]
        # 智慧切分：只抓後半段精華名字，讓側邊欄清爽好看
        short_title = associated_puzzle["title"].split("：")[-1]

        status_suffix = " 👑" if s_data["solved"] else ""
        btn_label = f"📝 {short_title}{status_suffix}"

        is_current = (s_id == st.session_state.active_session_id)

        if st.button(
            f"{'▶️ ' if is_current else ''}{btn_label}",
            key=s_id,
            use_container_width=True,
            type="secondary" if not is_current else "primary"
        ):
            st.session_state.active_session_id = s_id
            st.rerun()

# --- 讀取當前選中的資料 ---
cur_session = st.session_state.history_sessions[st.session_state.active_session_id]
puzzle = PUZZLES[cur_session["puzzle_index"]]

# --- 右側主畫面 ---
st.markdown("""
<div class="det-header">
    <div class="det-header-eyebrow">★ DETECTIVE CONAN CASE FILES ★</div>
    <h1>👓 名偵探柯南：米花町事件簿</h1>
    <div class="subtitle">「真相，永遠只有一個！」—— 運用你敏銳的觀察力質問犯人吧！</div>
</div>
""", unsafe_allow_html=True)

badges_html = "".join(f'<span class="case-badge">{g}</span>' for g in puzzle["genre"])

st.markdown(f"""
<div class="case-card">
    <div class="case-stamp">TARGET LOCKED</div>
    <div class="case-number">📂 {puzzle["tag"]}</div>
    <div class="case-title">🔍 當前調查案件：{puzzle["title"]}</div>
    <div style="margin-bottom:0.8rem">{badges_html}</div>
    <div class="case-body">{puzzle["question"]}</div>
</div>
""", unsafe_allow_html=True)

# 橫列資訊
col1, col2 = st.columns([2, 1])
with col1:
    if st.button("⚽ 切換下一案"):
        cur_session["puzzle_index"] = (cur_session["puzzle_index"] + 1) % len(PUZZLES)
        cur_session["chat_history"] = []
        cur_session["solved"] = False
        st.rerun()
with col2:
    clue_count = len([m for m in cur_session["chat_history"] if m["role"] == "user"])
    st.markdown(f'<div class="clue-counter">🎯 目前線索進度：{clue_count} 條</div>', unsafe_allow_html=True)

st.markdown("<hr style='border-color:#1e293b;'>", unsafe_allow_html=True)

# 渲染對話
for msg in cur_session["chat_history"]:
    if msg["role"] == "user":
        with st.chat_message("user", avatar="👓"):
            st.markdown(f'<div class="msg-user"><div class="label">🎀 蝴蝶結變聲器 · 偵探質問</div>{msg["content"]}</div>', unsafe_allow_html=True)
    else:
        with st.chat_message("assistant", avatar="👥"):
            if "案件告破" in msg["content"]:
                st.markdown(f'<div class="verdict-banner"><div class="v-title">🎯 麻醉針發射！沉睡的小五郎破案</div><div class="v-sub">{msg["content"]}</div></div>', unsafe_allow_html=True)
            elif "⚠️" in msg["content"]:
                st.error(msg["content"])
            else:
                st.markdown(f'<div class="msg-host"><div class="label">👥 犯人（黑影君）的回應</div><div class="verdict">{msg["content"]}</div></div>', unsafe_allow_html=True)

# 輸入控制
if not cur_session["solved"]:
    user_input = st.chat_input("🎯 輸入是非題（例如：這與時間或道具上有關嗎？）")
else:
    st.chat_input("🔒 犯人已伏法！請在左側點選『開啟全新調查紀錄』挑戰下一局。", disabled=True)
    user_input = None

if user_input:
    with st.chat_message("user", avatar="👓"):
        st.markdown(f'<div class="msg-user"><div class="label">🎀 蝴蝶結變聲器 · 偵探質問</div>{user_input}</div>', unsafe_allow_html=True)
    cur_session["chat_history"].append({"role": "user", "content": user_input})

    with st.spinner("▌ 正在透過偵探徽章分析線索..."):
        try:
            client = genai.Client(api_key=REAL_GEMINI_KEY)

            system_prompt = (
                "你現在是《名偵探柯南》中的黑影犯人，也是海龜湯遊戲主持人。\n"
                f"【當前案件謎題】：{puzzle['question']}\n"
                f"【背後隱藏真相】：{puzzle['answer']}\n\n"
                "【遊戲嚴格規則】\n"
                "1. 玩家會進行是非題詰問。你只能回答：『是』、『不是』、『不完全是』、『與本案無關』。嚴禁額外說明。\n"
                "2. 若玩家提問已經精準猜中【背後隱藏真相】的核心關鍵，請在回應最前面加上『[SOLVED]』。\n"
                "3. 字數嚴格限制在 50 字以內。"
            )

            prompt_context = f"{system_prompt}\n\n=== 歷史對話 ===\n"
            for m in cur_session["chat_history"][:-1]:
                label = "玩家" if m["role"] == "user" else "幕後黑手"
                if "⚠️" not in m["content"] and "案件告破" not in m["content"]:
                    prompt_context += f"{label}: {m['content']}\n"
            prompt_context += f"\n玩家最新提問：{user_input}\n你的單一精簡回應："

            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt_context
            )
            raw = response.text.strip()

            if "[SOLVED]" in raw:
                ai_response = f"「可惡...被看穿了嗎...」✨ 犯人心理防線崩潰！\n\n【完整真相卷宗】{puzzle['answer']}"
                cur_session["solved"] = True
                cur_session["chat_history"].append({"role": "assistant", "content": "案件告破！" + ai_response})
            else:
                if "不完全" in raw: final_reply = "❌ 不完全是"
                elif "無關" in raw: final_reply = "❌ 與本案無關"
                elif "不是" in raw or "否" in raw: final_reply = "❌ 不是"
                elif "是" in raw or "對" in raw: final_reply = "⭕ 是"
                else: final_reply = f"👥 {raw}"
                st.session_state.history_sessions[st.session_state.active_session_id]["chat_history"].append({"role": "assistant", "content": final_reply})

        except Exception as e:
            cur_session["chat_history"].append({"role": "assistant", "content": f"⚠️ 系統連線異常：{str(e)[:80]}"})

    st.rerun()

st.markdown('<div class="det-footer">TEITAN BOYS DETECTIVE CLUB · BEIKA CHO CASE ACADEMY · © 1996 GOSHO AOYAMA</div>', unsafe_allow_html=True)'''

# 3. 自動注入安全金鑰
app_code = app_code.replace("AUTO_INJECTED_API_KEY_HERE", my_api_key)

with open('app.py', 'w', encoding='utf-8') as f:
    f.write(app_code)

print("🎉 【終極完全體】八大案件＋標題智慧連動系統已完美建置！")

import os
import time

print("🧹 清除舊程序中...")
os.system("pkill -f streamlit")
os.system("pkill -f lt")
os.system("pkill -f ngrok")
os.system("rm -rf ~/.streamlit")
time.sleep(1)

print("🔍 正在啟動偵探海龜湯檔案室...")
os.system(
    "streamlit run app.py "
    "--server.port 8501 "
    "--server.enableCORS=false "
    "--server.enableXsrfProtection=false &"
)
time.sleep(4)

from google.colab import output
from google.colab.output import eval_js

colab_url = eval_js('google.colab.kernel.proxyPort(8501)')

print()
print("═" * 60)
print("  🔍 偵探海龜湯檔案室 — 傳送門已開啟")
print("═" * 60)
print(f"  👉 遊戲連結：{colab_url}")
print()
print("  📋 遊戲說明：")
print("     • 閱讀案件描述，對主持人提出是非題")
print("     • 主持人只會回答：是／不是／與案件無關／不完全是")
print("     • 猜出完整真相即破關！")
print("     • 點擊『調閱下一份檔案』可切換新案件")
print("═" * 60)

import google.generativeai as genai
from google.colab import userdata

print("🔍 正在進行 API Key 快速健檢...")

try:
    # 1. 抓取你存在左側面板的金鑰
    # ⚠️ 如果你左邊的名稱不是叫 GEMINI_API_KEY，請把下面這行的字改掉！
    my_key = userdata.get('GEMINI_API_KEY')

    # 印出前 5 個字元，確認有沒有抓到東西 (不用擔心，這很安全)
    if my_key:
        print(f"✅ 成功從密鑰面板抓到金鑰！前 5 碼為：{my_key[:5]}******")
    else:
        print("❌ 抓不到金鑰，請確認左側面板的名稱是否完全等於 'GEMINI_API_KEY'！")

    # 2. 直接向 Google 發送測試請求
    genai.configure(api_key=my_key)
    model = genai.GenerativeModel('gemini-1.5-flash')

    print("⏳ 正在向 Google 呼叫 AI...")
    response = model.generate_content("請回覆我『測試成功』四個字。")

    print("🤖 測試通過！AI 回覆：", response.text.strip())
    print("🎉 結論：你的 API Key 是正常的！如果是這樣，我們再來查其他原因。")

except Exception as e:
    print("\n❌ 測試失敗！錯誤訊息：", e)
    print("👉 結論：你的 API Key 真的無效（401錯誤）。")
    print("💡 解決辦法：請回到 Google AI Studio (aistudio.google.com)，重新建立一把全新的 API Key，然後覆蓋掉你 Colab 左側密鑰面板裡面的舊值！")

# 1. 強制安裝 Google 2026 最新官方 GenAI 套件
!pip install -q -U google-genai

from google import genai
from google.colab import userdata

print("🔍 正在使用全新官方 SDK 進行 API Key 健檢...")

try:
    my_key = userdata.get('GEMINI_API_KEY')
    if my_key:
        print(f"✅ 成功從密鑰面板抓到金鑰！前 5 碼為：{my_key[:5]}******")

        # 使用全新的 GenAI Client 連線機制
        client = genai.Client(api_key=my_key)

        print("⏳ 正在使用最新型 gemini-2.5-flash 呼叫 AI...")
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents='請回覆我『新版測試成功』六個字。',
        )

        print("\n🤖 測試通過！AI 回覆：", response.text.strip())
        print("🎉 太棒了！新版連線完全正常，404 障礙已排除了！")
    else:
        print("❌ 密鑰面板找不到 GEMINI_API_KEY，請確認名稱是否正確。")
except Exception as e:
    print("\n❌ 新版測試依舊失敗，錯誤原因：", e)